installExtensionFromFolder() - remove fill()
error: cy.get(...).fill is not a function

asume fill() comes from the package cypress-fill-command,
but this package is not installed and and solution is replaced by
cypress-native clear() + type(), because this was the only use of fill() in all functions

Tested with Cypress 13.3.0, with Joomla 4.3.4 and Joomla 5.0.0-rc