Let checkForPhpNoticesOrWarnings speak (#26)
* Let checkForPhpNoticesOrWarnings speak

Sometimes a PHP problem message directly in the HTML code causes rendering problems and
makes the error message invisible in the browser and on the screenshot. With this change
the PHP problem message is shown.

See the change by sample. Before:
```
  Test in frontend that the related items module
    1) "after each" hook for "can display a list of related articles based on the metakey field"

  0 passing (748ms)
  1 failing

  1) Test in frontend that the related items module
       "after each" hook for "can display a list of related articles based on the metakey field":
     AssertionError: expected true to equal false

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
      at Context.eval (webpack://joomla/./node_modules/joomla-cypress/src/support.js:98:0)
```

After:
```
  Test in frontend that the related items module
    1) "after each" hook for "can display a list of related articles based on the metakey field"

  0 passing (1s)
  1 failing

  1) Test in frontend that the related items module
       "after each" hook for "can display a list of related articles based on the metakey field":
     Error: Unwanted PHP Deprecated: "  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in <b>/Users/hlu/Desktop/no_backup/joomla-cms/libraries/src/Date/Date.php</b> on line <b>126</b>"

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
      at Context.eval (webpack://joomla/./node_modules/joomla-cypress/src/support.js:116:0)
```

* The method documentation for @returns rewritten