Fix clickToolbarButton Test
In PR #40 the `clickToolbarButton()` test was introduced, but it always fails with:
```
     CypressError: `cy.task('queryDB')` failed with the following error:

The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()
```

The Cypress custom task `queryDB` from Joomla System Tests is not available in testing joomla-cypress itself.

The error is reproducible when running the overall test suite or the single test:
```
npx cypress run --spec tests/e2e/support.cy.js --config-file tests/cypress.config.mjs
```

This PR manually implements the article deletion process .
Additionally, comments have been added to clarify what is being tested in the clickToolbarButton() test and
unified the button names with an initial uppercase letter, as capitalisation does not matter.
Please ensure that tests are always run after any changes to confirm that everything continues to function correctly.